lib/beebook_web/router.ex
defmodule BeebookWeb.Router do
  use BeebookWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug Phoenix.LiveView.Flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :auth do
    plug BeebookWeb.Helpers.AuthPlug
  end

  scope "/", BeebookWeb do
    pipe_through :browser

    get "/", PageController, :index

    # Sign in
    get "/signin", SessionController, :sign_in
    post "/signin", SessionController, :create_session

    # Sign up
    get "/signup", SessionController, :sign_up
    post "/signup", SessionController, :create_user
  end

  # User Scope
  scope "/", BeebookWeb do
    pipe_through [:browser, :auth]
    resources "/users", UserController, only: [:show, :edit, :update], singleton: true
    # Sign out
    post "/signout", SessionController, :sign_out

    live "/library", LibraryLive

    get "/dashboard", DashController, :index
    post "/dashboard", DashController, :update
  end

  # Other scopes may use custom stacks.
  # scope "/api", BeebookWeb do
  #   pipe_through :api
  # end
end

lib/beebook_web/templates/page/index.html.eex
<div>
  <div class="mb-4 md:ml-10">
    <h1 class="title"><b>Beebook</b></h1>
    <h3 class="subtitle">another bookmarking platform <br/> <i>from Oliveira & Stehlik</i> </h3>
  </div>

  <div class="md:flex">
    <div class="flex flex-col flex-shrink-0 w-40 mx-auto md:justify-center">
      <%= if signed_in?(@conn) do %>
        <%= link "Library", to: "/library", class: "button" %>
      <% else %>
        <%= link "Sign up", to: Routes.session_path(@conn, :sign_up), class: "button-confirm text-sm mb-3" %>
        <%= link "Sign in", to: Routes.session_path(@conn, :sign_in), class: "button-info text-sm" %>
      <% end %>
    </div>
    <div class="ml-auto my-3 max-w-md"><img src="<%= Routes.static_path(@conn, "/images/bookshelf.svg") %>" alt="Bookshelf" /></div>
  </div>
</div>